import { Country, Currency, PaymentMethod } from "../types/interfaces";
import { CgMoreO } from "react-icons/cg";
import { FaKitchenSet } from "react-icons/fa6";
import { GiClothes } from "react-icons/gi";
import { defaultColor } from "./colors";
import { GiRolledCloth } from "react-icons/gi";

export const Categories: string[] = [
  "Computer Science",
  "Mathematics",
  "Physics",
  "Chemistry",
  "Biology",
  "Mechanical Engineering",
  "Electrical Engineering",
  "Civil Engineering",
  "Control Engineering",
  "Software Engineering",
  "Hardware Engineering",
  "Data Science",
  "Machine Learning",
  "Deep Learning",
  "Artificial Intelligence",
  "Cyber Security",
  "Computer Engineering",
  "Blockchain",
  "Computer Programming",
  "Cloud Computing",
  "Web Development",
  "Exams/Tests",
];

export const Types: any = {
  "Exams/Tests": [
    "GRE",
    "GMAT",
    "TOEFL",
    "IELTS",
    "PTE",
    "SAT",
    "ACT",
    "LSAT",
    "MCAT",
    "USMLE",
    "NCLEX",
    "NAPLEX",
    "NBDE",
    "COMLEX",
    "CPA",
    "CFA",
    "FRM",
    "CAIA",
    "CMT",
    "CIPM",
    "CSCP",
    "CPIM",
    "CEP",
    "BEPC",
    "BAC A",
    "BAC B",
    "BAC C",
    "BAC D",
    "BAC E",
    "BAC F",
    "BAC G",
    "BAC H",
    "BAC I",
    "BAC J",
    "BAC K",
    "Biology",
    "Chemistry",
    "Physics",
    "Mathematics",
    "Computer Science",
    "Literature",
    "History",
    "Geography",
    "Economics",
  ],
  "Computer Science": [
    "Algorithms",
    "Data Structures",
    "Operating Systems",
    "Computer Graphics",
    "Computer Vision",
    "Computer Networks",
    "Computer Architecture",
    "Computer Organization",
    "Computer Programming",
    "Computer Software",
  ],
  Mathematics: [
    "Algebra",
    "Geometry",
    "Trigonometry",
    "Calculus",
    "Differential Equations",
    "Linear Algebra",
    "Probability",
    "Statistics",
    "Number Theory",
    "Discrete Mathematics",
    "Topology",
    "Complex Analysis",
    "Functional Analysis",
    "Real Analysis",
    "Numerical Analysis",
    "Mathematical Logic",
    "Mathematical Physics",
    "Mathematical Biology",
  ],
  Physics: [
    "Classical Mechanics",
    "Quantum Mechanics",
    "Thermodynamics",
    "Electromagnetism",
    "Optics",
    "Relativity",
    "Astrophysics",
    "Particle Physics",
    "Nuclear Physics",
    "Solid State Physics",
    "Plasma Physics",
    "Fluid Dynamics",
    "Acoustics",
    "Biophysics",
    "Geophysics",
    "Medical Physics",
    "Environmental Physics",
    "Engineering Physics",
  ],
  Chemistry: [
    "Physical Chemistry",
    "Inorganic Chemistry",
    "Organic Chemistry",
    "Analytical Chemistry",
    "Biochemistry",
    "Theoretical Chemistry",
    "Environmental Chemistry",
    "Medicinal Chemistry",
    "Polymer Chemistry",
    "Materials Chemistry",
    "Nuclear Chemistry",
    "Quantum Chemistry",
    "Computational Chemistry",
    "Industrial Chemistry",
    "Pharmaceutical Chemistry",
    "Forensic Chemistry",
    "Food Chemistry",
    "Geochemistry",
    "Atmospheric Chemistry",
    "Astrochemistry",
  ],
  Biology: [
    "Cell Biology",
    "Molecular Biology",
    "Genetics",
    "Biochemistry",
    "Microbiology",
    "Immunology",
    "Physiology",
    "Ecology",
    "Evolution",
    "Botany",
    "Zoology",
    "Marine Biology",
    "Biotechnology",
    "Bioinformatics",
    "Biophysics",
    "Biostatistics",
    "Biomedical Engineering",
    "Biomedicine",
    "Biopharmaceutics",
    "Biopsychology",
    "Biogeography",
    "Biosafety",
    "Biocatalysis",
    "Biocontrol",
    "Biodegradation",
  ],
  "Mechanical Engineering": [
    "Thermodynamics",
    "Fluid Mechanics",
    "Heat Transfer",
    "Machine Design",
  ],
  "Electrical Engineering": [
    "Circuit Theory",
    "Control Systems",
    "Electrical Machines",
    "Power Electronics",
    "Power Systems",
  ],
  "Civil Engineering": [
    "Structural Engineering",
    "Geotechnical Engineering",
    "Transportation Engineering",
    "Environmental Engineering",
  ],
  "Control Engineering": [
    "Control Theory",
    "Control Systems",
    "Automation",
    "Robotics",
  ],
  "Software Engineering": [
    "Software Development",
    "Software Testing",
    "Software Maintenance",
    "Software Design",
  ],
  "Hardware Engineering": [
    "Digital Electronics",
    "Analog Electronics",
    "Microprocessors",
    "Microcontrollers",
  ],
  "Data Science": [
    "Data Analysis",
    "Data Visualization",
    "Data Mining",
    "Machine Learning",
    "Deep Learning",
    "Artificial Intelligence",
  ],
  "Machine Learning": [
    "Supervised Learning",
    "Unsupervised Learning",
    "Reinforcement Learning",
    "Deep Learning",
    "Neural Networks",
    "Convolutional Neural Networks",
    "Recurrent Neural Networks",
    "Generative Adversarial Networks",
  ],
  "Deep Learning": [
    "Neural Networks",
    "Convolutional Neural Networks",
    "Recurrent Neural Networks",
    "Generative Adversarial Networks",
  ],
  "Artificial Intelligence": [
    "Expert Systems",
    "Fuzzy Logic",
    "Genetic Algorithms",
    "Machine Learning",
    "Deep Learning",
    "Natural Language Processing",
    "Computer Vision",
    "Robotics",
    "Cyber Security",
  ],
  "Cyber Security": [
    "Network Security",
    "Web Security",
    "Mobile Security",
    "Cloud Security",
    "IoT Security",
    "Blockchain Security",
  ],
  "Computer Engineering": [
    "Computer Science",
    "Software Engineering",
    "Hardware Engineering",
    "Data Science",
    "Machine Learning",
    "Deep Learning",
    "Artificial Intelligence",
    "Robotics",
    "Cyber Security",
  ],
  "Computer Programming": [
    "c",
    "c++",
    "java",
    "python",
    "javascript",
    "typescript",
    "php",
    "ruby",
    "perl",
    "swift",
    "kotlin",
    "dart",
    "go",
    "rust",
    "flutter",
  ],
  "Web Development": [
    "html",
    "css",
    "javascript",
    "typescript",
    "react",
    "angular",
    "vue",
    "svelte",
    "next",
    "nuxt",
    "gatsby",
    "sapper",
    "express",
    "koa",
    "nestjs",
    "django",
    "flask",
    "laravel",
    "symfony",
    "ruby on rails",
    "asp.net",
    "spring",
    "strapi",
    "wordpress",
    "joomla",
    "drupal",
    "magento",
    "shopify",
    "wix",
    "squarespace",
    "weebly",
  ],
  "Cloud Computing": [
    "aws",
    "azure",
    "google cloud",
    "ibm cloud",
    "oracle cloud",
    "alibaba cloud",
    "tencent cloud",
    "digital ocean",
    "linode",
    "vultr",
    "heroku",
    "netlify",
    "vercel",
    "firebase",
    "cloudflare",
    "fastly",
    "akamai",
    "cloudinary",
    "imgix",
    "cloudinary",
    "imgix",
    "firebase",
  ],
  Blockchain: [
    "solidity",
    "web3",
    "truffle",
    "ganache",
    "hardhat",
    "cryptography",
  ],
};

export const countries: Country[] = [
  {
    name: "Afghanistan",
    dial_code: "+93",
    code: "AF",
    continent: "Asia",
    native: "افغانستان",
    currency: "AFN",
  },
  {
    name: "Aland Islands",
    dial_code: "+358",
    code: "AX",
    continent: "Europe",
    native: "Åland",
    currency: "EUR",
  },
  {
    name: "Albania",
    dial_code: "+355",
    code: "AL",
    continent: "Europe",
    native: "Shqipëria",
    currency: "ALL",
  },
  {
    name: "Algeria",
    dial_code: "+213",
    code: "DZ",
    continent: "Africa",
    native: "الجزائر",
    currency: "DZD",
  },
  {
    name: "AmericanSamoa",
    dial_code: "+1684",
    code: "AS",
    continent: "Oceania",
    native: "American Samoa",
    currency: "USD",
  },
  {
    name: "Andorra",
    dial_code: "+376",
    code: "AD",
    continent: "Europe",
    native: "Andorra",
    currency: "EUR",
  },
  {
    name: "Angola",
    dial_code: "+244",
    code: "AO",
    continent: "Africa",
    native: "Angola",
    currency: "AOA",
  },
  {
    name: "Anguilla",
    dial_code: "+1264",
    code: "AI",
    continent: "North America",
    native: "Anguilla",
    currency: "XCD",
  },
  // {
  //   name: "Antarctica",
  //   dial_code: "+672",
  //   code: "AQ",
  //   continent: "Antarctica",
  //   native: "Antarctica",
  //   currency: "",
  // },
  {
    name: "Antigua and Barbuda",
    dial_code: "+1268",
    code: "AG",
    continent: "North America",
    native: "Antigua and Barbuda",
    currency: "XCD",
  },
  {
    name: "Argentina",
    dial_code: "+54",
    code: "AR",
    continent: "South America",
    native: "Argentina",
    currency: "ARS",
  },
  {
    name: "Armenia",
    dial_code: "+374",
    code: "AM",
    continent: "Asia",
    native: "Հայաստան",
    currency: "AMD",
  },
  {
    name: "Aruba",
    dial_code: "+297",
    code: "AW",
    continent: "North America",
    native: "Aruba",
    currency: "AWG",
  },
  {
    name: "Australia",
    dial_code: "+61",
    code: "AU",
    continent: "Oceania",
    native: "Australia",
    currency: "AUD",
  },
  {
    name: "Austria",
    dial_code: "+43",
    code: "AT",
    continent: "Europe",
    native: "Österreich",
    currency: "EUR",
  },
  {
    name: "Azerbaijan",
    dial_code: "+994",
    code: "AZ",
    continent: "Asia",
    native: "Azərbaycan",
    currency: "AZN",
  },
  {
    name: "Bahamas",
    dial_code: "+1242",
    code: "BS",
    continent: "North America",
    native: "Bahamas",
    currency: "BSD",
  },
  {
    name: "Bahrain",
    dial_code: "+973",
    code: "BH",
    continent: "Asia",
    native: "‏البحرين",
    currency: "BHD",
  },
  {
    name: "Bangladesh",
    dial_code: "+880",
    code: "BD",
    continent: "Asia",
    native: "Bangladesh",
    currency: "BDT",
  },
  {
    name: "Barbados",
    dial_code: "+1246",
    code: "BB",
    continent: "North America",
    native: "Barbados",
    currency: "BBD",
  },
  {
    name: "Belarus",
    dial_code: "+375",
    code: "BY",
    continent: "Europe",
    native: "Белару́сь",
    currency: "BYR",
  },
  {
    name: "Belgium",
    dial_code: "+32",
    code: "BE",
    continent: "Europe",
    native: "België",
    currency: "EUR",
  },
  {
    name: "Belize",
    dial_code: "+501",
    code: "BZ",
    continent: "North America",
    native: "Belize",
    currency: "BZD",
  },
  {
    name: "Benin",
    dial_code: "+229",
    code: "BJ",
    continent: "Africa",
    native: "Bénin",
    currency: "XOF",
  },
  {
    name: "Bermuda",
    dial_code: "+1441",
    code: "BM",
    continent: "North America",
    native: "Bermuda",
    currency: "BMD",
  },
  {
    name: "Bhutan",
    dial_code: "+975",
    code: "BT",
    continent: "Asia",
    native: "ʼbrug-yul",
    currency: "BTN",
  },
  {
    name: "Bolivia, Plurinational State of",
    dial_code: "+591",
    code: "BO",
    continent: "South America",
    native: "Bolivia",
    currency: "BOB",
  },
  {
    name: "Bosnia and Herzegovina",
    dial_code: "+387",
    code: "BA",
    continent: "Europe",
    native: "Bosna i Hercegovina",
    currency: "BAM",
  },
  {
    name: "Botswana",
    dial_code: "+267",
    code: "BW",
    continent: "Africa",
    native: "Botswana",
    currency: "BWP",
  },
  {
    name: "Brazil",
    dial_code: "+55",
    code: "BR",
    continent: "South America",
    native: "Brasil",
    currency: "BRL",
  },
  {
    name: "British Indian Ocean Territory",
    dial_code: "+246",
    code: "IO",
    continent: "Asia",
    native: "British Indian Ocean Territory",
    currency: "USD",
  },
  {
    name: "Brunei Darussalam",
    dial_code: "+673",
    code: "BN",
    continent: "Asia",
    native: "Negara Brunei Darussalam",
    currency: "BND",
  },
  {
    name: "Bulgaria",
    dial_code: "+359",
    code: "BG",
    continent: "Europe",
    native: "България",
    currency: "BGN",
  },
  {
    name: "Burkina Faso",
    dial_code: "+226",
    code: "BF",
    continent: "Africa",
    native: "Burkina Faso",
    currency: "XOF",
  },
  {
    name: "Burundi",
    dial_code: "+257",
    code: "BI",
    continent: "Africa",
    native: "Burundi",
    currency: "BIF",
  },
  {
    name: "Cambodia",
    dial_code: "+855",
    code: "KH",
    continent: "Asia",
    native: "Kâmpŭchéa",
    currency: "KHR",
  },
  {
    name: "Cameroon",
    dial_code: "+237",
    code: "CM",
    continent: "Africa",
    native: "Cameroon",
    currency: "XAF",
  },
  {
    name: "Canada",
    dial_code: "+1",
    code: "CA",
    continent: "North America",
    native: "Canada",
    currency: "CAD",
  },
  {
    name: "Cape Verde",
    dial_code: "+238",
    code: "CV",
    continent: "Africa",
    native: "Cabo Verde",
    currency: "CVE",
  },
  {
    name: "Cayman Islands",
    dial_code: "+ 345",
    code: "KY",
    continent: "North America",
    native: "Cayman Islands",
    currency: "KYD",
  },
  {
    name: "Central African Republic",
    dial_code: "+236",
    code: "CF",
    continent: "Africa",
    native: "Ködörösêse tî Bêafrîka",
    currency: "XAF",
  },
  {
    name: "Chad",
    dial_code: "+235",
    code: "TD",
    continent: "Africa",
    native: "Tchad",
    currency: "XAF",
  },
  {
    name: "Chile",
    dial_code: "+56",
    code: "CL",
    continent: "South America",
    native: "Chile",
    currency: "CLP",
  },
  {
    name: "China",
    dial_code: "+86",
    code: "CN",
    continent: "Asia",
    native: "中国",
    currency: "CNY",
  },
  {
    name: "Christmas Island",
    dial_code: "+61",
    code: "CX",
    continent: "Asia",
    native: "Christmas Island",
    currency: "AUD",
  },
  {
    name: "Cocos (Keeling) Islands",
    dial_code: "+61",
    code: "CC",
    continent: "Asia",
    native: "Cocos (Keeling) Islands",
    currency: "AUD",
  },
  {
    name: "Colombia",
    dial_code: "+57",
    code: "CO",
    continent: "South America",
    native: "Colombia",
    currency: "COP",
  },
  {
    name: "Comoros",
    dial_code: "+269",
    code: "KM",
    continent: "Africa",
    native: "Komori",
    currency: "KMF",
  },
  {
    name: "Congo",
    dial_code: "+242",
    code: "CG",
    continent: "Africa",
    native: "République du Congo",
    currency: "XAF",
  },
  {
    name: "Congo, The Democratic Republic of the Congo",
    dial_code: "+243",
    code: "CD",
    continent: "Africa",
    native: "République démocratique du Congo",
    currency: "CDF",
  },
  {
    name: "Cook Islands",
    dial_code: "+682",
    code: "CK",
    continent: "Oceania",
    native: "Cook Islands",
    currency: "NZD",
  },
  {
    name: "Costa Rica",
    dial_code: "+506",
    code: "CR",
    continent: "North America",
    native: "Costa Rica",
    currency: "CRC",
  },
  {
    name: "Cote d'Ivoire",
    dial_code: "+225",
    code: "CI",
    continent: "Africa",
    native: "Côte d'Ivoire",
    currency: "XOF",
  },
  {
    name: "Croatia",
    dial_code: "+385",
    code: "HR",
    continent: "Europe",
    native: "Hrvatska",
    currency: "HRK",
  },
  {
    name: "Cuba",
    dial_code: "+53",
    code: "CU",
    continent: "North America",
    native: "Cuba",
    currency: "CUP",
  },
  {
    name: "Cyprus",
    dial_code: "+357",
    code: "CY",
    continent: "Europe",
    native: "Κύπρος",
    currency: "EUR",
  },
  {
    name: "Czech Republic",
    dial_code: "+420",
    code: "CZ",
    continent: "Europe",
    native: "Česká republika",
    currency: "CZK",
  },
  {
    name: "Denmark",
    dial_code: "+45",
    code: "DK",
    continent: "Europe",
    native: "Danmark",
    currency: "DKK",
  },
  {
    name: "Djibouti",
    dial_code: "+253",
    code: "DJ",
    continent: "Africa",
    native: "Djibouti",
    currency: "DJF",
  },
  {
    name: "Dominica",
    dial_code: "+1767",
    code: "DM",
    continent: "North America",
    native: "Dominica",
    currency: "XCD",
  },
  {
    name: "Dominican Republic",
    dial_code: "+1849",
    code: "DO",
    continent: "North America",
    native: "República Dominicana",
    currency: "DOP",
  },
  {
    name: "Ecuador",
    dial_code: "+593",
    code: "EC",
    continent: "South America",
    native: "Ecuador",
    currency: "USD",
  },
  {
    name: "Egypt",
    dial_code: "+20",
    code: "EG",
    continent: "Africa",
    native: "مصر",
    currency: "EGP",
  },
  {
    name: "El Salvador",
    dial_code: "+503",
    code: "SV",
    continent: "North America",
    native: "El Salvador",
    currency: "USD",
  },
  {
    name: "Equatorial Guinea",
    dial_code: "+240",
    code: "GQ",
    continent: "Africa",
    native: "Guinea Ecuatorial",
    currency: "XAF",
  },
  {
    name: "Eritrea",
    dial_code: "+291",
    code: "ER",
    continent: "Africa",
    native: "ኤርትራ",
    currency: "ERN",
  },
  {
    name: "Estonia",
    dial_code: "+372",
    code: "EE",
    continent: "Europe",
    native: "Eesti",
    currency: "EUR",
  },
  {
    name: "Ethiopia",
    dial_code: "+251",
    code: "ET",
    continent: "Africa",
    native: "ኢትዮጵያ",
    currency: "ETB",
  },
  {
    name: "Falkland Islands (Malvinas)",
    dial_code: "+500",
    code: "FK",
    continent: "South America",
    native: "Falkland Islands",
    currency: "FKP",
  },
  {
    name: "Faroe Islands",
    dial_code: "+298",
    code: "FO",
    continent: "Europe",
    native: "Føroyar",
    currency: "DKK",
  },
  {
    name: "Fiji",
    dial_code: "+679",
    code: "FJ",
    continent: "Oceania",
    native: "Fiji",
    currency: "FJD",
  },
  {
    name: "Finland",
    dial_code: "+358",
    code: "FI",
    continent: "Europe",
    native: "Suomi",
    currency: "EUR",
  },
  {
    name: "France",
    dial_code: "+33",
    code: "FR",
    continent: "Europe",
    native: "France",
    currency: "EUR",
  },
  {
    name: "French Guiana",
    dial_code: "+594",
    code: "GF",
    continent: "South America",
    native: "Guyane française",
    currency: "EUR",
  },
  {
    name: "French Polynesia",
    dial_code: "+689",
    code: "PF",
    continent: "Oceania",
    native: "Polynésie française",
    currency: "XPF",
  },
  {
    name: "Gabon",
    dial_code: "+241",
    code: "GA",
    continent: "Africa",
    native: "Gabon",
    currency: "XAF",
  },
  {
    name: "Gambia",
    dial_code: "+220",
    code: "GM",
    continent: "Africa",
    native: "Gambia",
    currency: "GMD",
  },
  {
    name: "Georgia",
    dial_code: "+995",
    code: "GE",
    continent: "Asia",
    native: "საქართველო",
    currency: "GEL",
  },
  {
    name: "Germany",
    dial_code: "+49",
    code: "DE",
    continent: "Europe",
    native: "Deutschland",
    currency: "EUR",
  },
  {
    name: "Ghana",
    dial_code: "+233",
    code: "GH",
    continent: "Africa",
    native: "Ghana",
    currency: "GHS",
  },
  {
    name: "Gibraltar",
    dial_code: "+350",
    code: "GI",
    continent: "Europe",
    native: "Gibraltar",
    currency: "GIP",
  },
  {
    name: "Greece",
    dial_code: "+30",
    code: "GR",
    continent: "Europe",
    native: "Ελλάδα",
    currency: "EUR",
  },
  {
    name: "Greenland",
    dial_code: "+299",
    code: "GL",
    continent: "North America",
    native: "Kalaallit Nunaat",
    currency: "DKK",
  },
  {
    name: "Grenada",
    dial_code: "+1473",
    code: "GD",
    continent: "North America",
    native: "Grenada",
    currency: "XCD",
  },
  {
    name: "Guadeloupe",
    dial_code: "+590",
    code: "GP",
    continent: "North America",
    native: "Guadeloupe",
    currency: "EUR",
  },
  {
    name: "Guam",
    dial_code: "+1671",
    code: "GU",
    continent: "Oceania",
    native: "Guam",
    currency: "USD",
  },
  {
    name: "Guatemala",
    dial_code: "+502",
    code: "GT",
    continent: "North America",
    native: "Guatemala",
    currency: "GTQ",
  },
  {
    name: "Guernsey",
    dial_code: "+44",
    code: "GG",
    continent: "Europe",
    native: "Guernsey",
    currency: "GBP",
  },
  {
    name: "Guinea",
    dial_code: "+224",
    code: "GN",
    continent: "Africa",
    native: "Guinée",
    currency: "GNF",
  },
  {
    name: "Guinea-Bissau",
    dial_code: "+245",
    code: "GW",
    continent: "Africa",
    native: "Guiné-Bissau",
    currency: "XOF",
  },
  {
    name: "Guyana",
    dial_code: "+595",
    code: "GY",
    continent: "South America",
    native: "Guyana",
    currency: "GYD",
  },
  {
    name: "Haiti",
    dial_code: "+509",
    code: "HT",
    continent: "North America",
    native: "Haïti",
    currency: "HTG",
  },
  {
    name: "Holy See (Vatican City State)",
    dial_code: "+379",
    code: "VA",
    continent: "Europe",
    native: "Vaticano",
    currency: "EUR",
  },
  {
    name: "Honduras",
    dial_code: "+504",
    code: "HN",
    continent: "North America",
    native: "Honduras",
    currency: "HNL",
  },
  {
    name: "Hong Kong",
    dial_code: "+852",
    code: "HK",
    continent: "Asia",
    native: "香港",
    currency: "HKD",
  },
  {
    name: "Hungary",
    dial_code: "+36",
    code: "HU",
    continent: "Europe",
    native: "Magyarország",
    currency: "HUF",
  },
  {
    name: "Iceland",
    dial_code: "+354",
    code: "IS",
    continent: "Europe",
    native: "Ísland",
    currency: "ISK",
  },
  {
    name: "India",
    dial_code: "+91",
    code: "IN",
    continent: "Asia",
    native: "भारत",
    currency: "INR",
  },
  {
    name: "Indonesia",
    dial_code: "+62",
    code: "ID",
    continent: "Asia",
    native: "Indonesia",
    currency: "IDR",
  },
  {
    name: "Iran, Islamic Republic of Persian Gulf",
    dial_code: "+98",
    code: "IR",
    continent: "Asia",
    native: "ایران",
    currency: "IRR",
  },
  {
    name: "Iraq",
    dial_code: "+964",
    code: "IQ",
    continent: "Asia",
    native: "العراق",
    currency: "IQD",
  },
  {
    name: "Ireland",
    dial_code: "+353",
    code: "IE",
    continent: "Europe",
    native: "Éire",
    currency: "EUR",
  },
  {
    name: "Isle of Man",
    dial_code: "+44",
    code: "IM",
    continent: "Europe",
    native: "Isle of Man",
    currency: "GBP",
  },
  {
    name: "Israel",
    dial_code: "+972",
    code: "IL",
    continent: "Asia",
    native: "יִשְׂרָאֵל",
    currency: "ILS",
  },
  {
    name: "Italy",
    dial_code: "+39",
    code: "IT",
    continent: "Europe",
    native: "Italia",
    currency: "EUR",
  },
  {
    name: "Jamaica",
    dial_code: "+1876",
    code: "JM",
    continent: "North America",
    native: "Jamaica",
    currency: "JMD",
  },
  {
    name: "Japan",
    dial_code: "+81",
    code: "JP",
    continent: "Asia",
    native: "日本",
    currency: "JPY",
  },
  {
    name: "Jersey",
    dial_code: "+44",
    code: "JE",
    continent: "Europe",
    native: "Jersey",
    currency: "GBP",
  },
  {
    name: "Jordan",
    dial_code: "+962",
    code: "JO",
    continent: "Asia",
    native: "الأردن",
    currency: "JOD",
  },
  {
    name: "Kazakhstan",
    dial_code: "+77",
    code: "KZ",
    continent: "Asia",
    native: "Қазақстан",
    currency: "KZT",
  },
  {
    name: "Kenya",
    dial_code: "+254",
    code: "KE",
    continent: "Africa",
    native: "Kenya",
    currency: "KES",
  },
  {
    name: "Kiribati",
    dial_code: "+686",
    code: "KI",
    continent: "Oceania",
    native: "Kiribati",
    currency: "AUD",
  },
  {
    name: "Korea, Democratic People's Republic of Korea",
    dial_code: "+850",
    code: "KP",
    continent: "Asia",
    native: "북한",
    currency: "KPW",
  },
  {
    name: "Korea, Republic of South Korea",
    dial_code: "+82",
    code: "KR",
    continent: "Asia",
    native: "대한민국",
    currency: "KRW",
  },
  {
    name: "Kuwait",
    dial_code: "+965",
    code: "KW",
    continent: "Asia",
    native: "الكويت",
    currency: "KWD",
  },
  {
    name: "Kyrgyzstan",
    dial_code: "+996",
    code: "KG",
    continent: "Asia",
    native: "Кыргызстан",
    currency: "KGS",
  },
  {
    name: "Laos",
    dial_code: "+856",
    code: "LA",
    continent: "Asia",
    native: "ສປປລາວ",
    currency: "LAK",
  },
  {
    name: "Latvia",
    dial_code: "+371",
    code: "LV",
    continent: "Europe",
    native: "Latvija",
    currency: "EUR",
  },
  {
    name: "Lebanon",
    dial_code: "+961",
    code: "LB",
    continent: "Asia",
    native: "لبنان",
    currency: "LBP",
  },
  {
    name: "Lesotho",
    dial_code: "+266",
    code: "LS",
    continent: "Africa",
    native: "Lesotho",
    currency: "LSL",
  },
  {
    name: "Liberia",
    dial_code: "+231",
    code: "LR",
    continent: "Africa",
    native: "Liberia",
    currency: "LRD",
  },
  {
    name: "Libyan Arab Jamahiriya",
    dial_code: "+218",
    code: "LY",
    continent: "Africa",
    native: "‏ليبيا",
    currency: "LYD",
  },
  {
    name: "Liechtenstein",
    dial_code: "+423",
    code: "LI",
    continent: "Europe",
    native: "Liechtenstein",
    currency: "CHF",
  },
  {
    name: "Lithuania",
    dial_code: "+370",
    code: "LT",
    continent: "Europe",
    native: "Lietuva",
    currency: "EUR",
  },
  {
    name: "Luxembourg",
    dial_code: "+352",
    code: "LU",
    continent: "Europe",
    native: "Luxembourg",
    currency: "EUR",
  },
  {
    name: "Macao",
    dial_code: "+853",
    code: "MO",
    continent: "Asia",
    native: "澳門",
    currency: "MOP",
  },
  {
    name: "Macedonia",
    dial_code: "+389",
    code: "MK",
    continent: "Europe",
    native: "Македонија",
    currency: "MKD",
  },
  {
    name: "Madagascar",
    dial_code: "+261",
    code: "MG",
    continent: "Africa",
    native: "Madagasikara",
    currency: "MGA",
  },
  {
    name: "Malawi",
    dial_code: "+265",
    code: "MW",
    continent: "Africa",
    native: "Malawi",
    currency: "MWK",
  },
  {
    name: "Malaysia",
    dial_code: "+60",
    code: "MY",
    continent: "Asia",
    native: "Malaysia",
    currency: "MYR",
  },
  {
    name: "Maldives",
    dial_code: "+960",
    code: "MV",
    continent: "Asia",
    native: "Maldives",
    currency: "MVR",
  },
  {
    name: "Mali",
    dial_code: "+223",
    code: "ML",
    continent: "Africa",
    native: "Mali",
    currency: "XOF",
  },
  {
    name: "Malta",
    dial_code: "+356",
    code: "MT",
    continent: "Europe",
    native: "Malta",
    currency: "EUR",
  },
  {
    name: "Marshall Islands",
    dial_code: "+692",
    code: "MH",
    continent: "Oceania",
    native: "M̧ajeļ",
    currency: "USD",
  },
  {
    name: "Martinique",
    dial_code: "+596",
    code: "MQ",
    continent: "North America",
    native: "Martinique",
    currency: "EUR",
  },
  {
    name: "Mauritania",
    dial_code: "+222",
    code: "MR",
    continent: "Africa",
    native: "موريتانيا",
    currency: "MRO",
  },
  {
    name: "Mauritius",
    dial_code: "+230",
    code: "MU",
    continent: "Africa",
    native: "Maurice",
    currency: "MUR",
  },
  {
    name: "Mayotte",
    dial_code: "+262",
    code: "YT",
    continent: "Africa",
    native: "Mayotte",
    currency: "EUR",
  },
  {
    name: "Mexico",
    dial_code: "+52",
    code: "MX",
    continent: "North America",
    native: "México",
    currency: "MXN",
  },
  {
    name: "Micronesia, Federated States of Micronesia",
    dial_code: "+691",
    code: "FM",
    continent: "Oceania",
    native: "Micronesia",
    currency: "USD",
  },
  {
    name: "Moldova",
    dial_code: "+373",
    code: "MD",
    continent: "Europe",
    native: "Moldova",
    currency: "MDL",
  },
  {
    name: "Monaco",
    dial_code: "+377",
    code: "MC",
    continent: "Europe",
    native: "Monaco",
    currency: "EUR",
  },
  {
    name: "Mongolia",
    dial_code: "+976",
    code: "MN",
    continent: "Asia",
    native: "Монгол улс",
    currency: "MNT",
  },
  {
    name: "Montenegro",
    dial_code: "+382",
    code: "ME",
    continent: "Europe",
    native: "Црна Гора",
    currency: "EUR",
  },
  {
    name: "Montserrat",
    dial_code: "+1664",
    code: "MS",
    continent: "North America",
    native: "Montserrat",
    currency: "XCD",
  },
  {
    name: "Morocco",
    dial_code: "+212",
    code: "MA",
    continent: "Africa",
    native: "المغرب",
    currency: "MAD",
  },
  {
    name: "Mozambique",
    dial_code: "+258",
    code: "MZ",
    continent: "Africa",
    native: "Moçambique",
    currency: "MZN",
  },
  {
    name: "Myanmar",
    dial_code: "+95",
    code: "MM",
    continent: "Asia",
    native: "Myanma",
    currency: "MMK",
  },
  {
    name: "Namibia",
    dial_code: "+264",
    code: "NA",
    continent: "Africa",
    native: "Namibia",
    currency: "NAD",
  },
  {
    name: "Nauru",
    dial_code: "+674",
    code: "NR",
    continent: "Oceania",
    native: "Nauru",
    currency: "AUD",
  },
  {
    name: "Nepal",
    dial_code: "+977",
    code: "NP",
    continent: "Asia",
    native: "नपल",
    currency: "NPR",
  },
  {
    name: "Netherlands",
    dial_code: "+31",
    code: "NL",
    continent: "Europe",
    native: "Nederland",
    currency: "EUR",
  },
  {
    name: "Netherlands Antilles",
    dial_code: "+599",
    code: "AN",
    continent: "North America",
    native: "Netherlands Antilles",
    currency: "ANG",
  },
  {
    name: "New Caledonia",
    dial_code: "+687",
    code: "NC",
    continent: "Oceania",
    native: "Nouvelle-Calédonie",
    currency: "XPF",
  },
  {
    name: "New Zealand",
    dial_code: "+64",
    code: "NZ",
    continent: "Oceania",
    native: "New Zealand",
    currency: "NZD",
  },
  {
    name: "Nicaragua",
    dial_code: "+505",
    code: "NI",
    continent: "North America",
    native: "Nicaragua",
    currency: "NIO",
  },
  {
    name: "Niger",
    dial_code: "+227",
    code: "NE",
    continent: "Africa",
    native: "Niger",
    currency: "XOF",
  },
  {
    name: "Nigeria",
    dial_code: "+234",
    code: "NG",
    continent: "Africa",
    native: "Nigeria",
    currency: "NGN",
  },
  {
    name: "Niue",
    dial_code: "+683",
    code: "NU",
    continent: "Oceania",
    native: "Niuē",
    currency: "NZD",
  },
  {
    name: "Norfolk Island",
    dial_code: "+672",
    code: "NF",
    continent: "Oceania",
    native: "Norfolk Island",
    currency: "AUD",
  },
  {
    name: "Northern Mariana Islands",
    dial_code: "+1670",
    code: "MP",
    continent: "Oceania",
    native: "Northern Mariana Islands",
    currency: "USD",
  },
  {
    name: "Norway",
    dial_code: "+47",
    code: "NO",
    continent: "Europe",
    native: "Norge",
    currency: "NOK",
  },
  {
    name: "Oman",
    dial_code: "+968",
    code: "OM",
    continent: "Asia",
    native: "عمان",
    currency: "OMR",
  },
  {
    name: "Pakistan",
    dial_code: "+92",
    code: "PK",
    continent: "Asia",
    native: "Pakistan",
    currency: "PKR",
  },
  {
    name: "Palau",
    dial_code: "+680",
    code: "PW",
    continent: "Oceania",
    native: "Palau",
    currency: "USD",
  },
  {
    name: "Palestinian Territory, Occupied",
    dial_code: "+970",
    code: "PS",
    continent: "Asia",
    native: "فلسطين",
    currency: "ILS",
  },
  {
    name: "Panama",
    dial_code: "+507",
    code: "PA",
    continent: "North America",
    native: "Panamá",
    currency: "PAB",
  },
  {
    name: "Papua New Guinea",
    dial_code: "+675",
    code: "PG",
    continent: "Oceania",
    native: "Papua Niugini",
    currency: "PGK",
  },
  {
    name: "Paraguay",
    dial_code: "+595",
    code: "PY",
    continent: "South America",
    native: "Paraguay",
    currency: "PYG",
  },
  {
    name: "Peru",
    dial_code: "+51",
    code: "PE",
    continent: "South America",
    native: "Perú",
    currency: "PEN",
  },
  {
    name: "Philippines",
    dial_code: "+63",
    code: "PH",
    continent: "Asia",
    native: "Pilipinas",
    currency: "PHP",
  },
  {
    name: "Pitcairn",
    dial_code: "+872",
    code: "PN",
    continent: "Oceania",
    native: "Pitcairn Islands",
    currency: "NZD",
  },
  {
    name: "Poland",
    dial_code: "+48",
    code: "PL",
    continent: "Europe",
    native: "Polska",
    currency: "PLN",
  },
  {
    name: "Portugal",
    dial_code: "+351",
    code: "PT",
    continent: "Europe",
    native: "Portugal",
    currency: "EUR",
  },
  {
    name: "Puerto Rico",
    dial_code: "+1939",
    code: "PR",
    continent: "North America",
    native: "Puerto Rico",
    currency: "USD",
  },
  {
    name: "Qatar",
    dial_code: "+974",
    code: "QA",
    continent: "Asia",
    native: "قطر",
    currency: "QAR",
  },
  {
    name: "Romania",
    dial_code: "+40",
    code: "RO",
    continent: "Europe",
    native: "România",
    currency: "RON",
  },
  {
    name: "Russia",
    dial_code: "+7",
    code: "RU",
    continent: "Europe",
    native: "Россия",
    currency: "RUB",
  },
  {
    name: "Rwanda",
    dial_code: "+250",
    code: "RW",
    continent: "Africa",
    native: "Rwanda",
    currency: "RWF",
  },
  {
    name: "Reunion",
    dial_code: "+262",
    code: "RE",
    continent: "Africa",
    native: "Réunion",
    currency: "EUR",
  },
  {
    name: "Saint Barthelemy",
    dial_code: "+590",
    code: "BL",
    continent: "North America",
    native: "Saint-Barthélemy",
    currency: "EUR",
  },
  {
    name: "Saint Helena, Ascension and Tristan Da Cunha",
    dial_code: "+290",
    code: "SH",
    continent: "Africa",
    native: "Saint Helena",
    currency: "SHP",
  },
  {
    name: "Saint Kitts and Nevis",
    dial_code: "+1869",
    code: "KN",
    continent: "North America",
    native: "Saint Kitts and Nevis",
    currency: "XCD",
  },
  {
    name: "Saint Lucia",
    dial_code: "+1758",
    code: "LC",
    continent: "North America",
    native: "Saint Lucia",
    currency: "XCD",
  },
  {
    name: "Saint Martin",
    dial_code: "+590",
    code: "MF",
    continent: "North America",
    native: "Saint-Martin",
    currency: "EUR",
  },
  {
    name: "Saint Pierre and Miquelon",
    dial_code: "+508",
    code: "PM",
    continent: "North America",
    native: "Saint-Pierre-et-Miquelon",
    currency: "EUR",
  },
  {
    name: "Saint Vincent and the Grenadines",
    dial_code: "+1784",
    code: "VC",
    continent: "North America",
    native: "Saint Vincent and the Grenadines",
    currency: "XCD",
  },
  {
    name: "Samoa",
    dial_code: "+685",
    code: "WS",
    continent: "Oceania",
    native: "Samoa",
    currency: "WST",
  },
  {
    name: "San Marino",
    dial_code: "+378",
    code: "SM",
    continent: "Europe",
    native: "San Marino",
    currency: "EUR",
  },
  {
    name: "Sao Tome and Principe",
    dial_code: "+239",
    code: "ST",
    continent: "Africa",
    native: "São Tomé e Príncipe",
    currency: "STD",
  },
  {
    name: "Saudi Arabia",
    dial_code: "+966",
    code: "SA",
    continent: "Asia",
    native: "العربية السعودية",
    currency: "SAR",
  },
  {
    name: "Senegal",
    dial_code: "+221",
    code: "SN",
    continent: "Africa",
    native: "Sénégal",
    currency: "XOF",
  },
  {
    name: "Serbia",
    dial_code: "+381",
    code: "RS",
    continent: "Europe",
    native: "Србија",
    currency: "RSD",
  },
  {
    name: "Seychelles",
    dial_code: "+248",
    code: "SC",
    continent: "Africa",
    native: "Seychelles",
    currency: "SCR",
  },
  {
    name: "Sierra Leone",
    dial_code: "+232",
    code: "SL",
    continent: "Africa",
    native: "Sierra Leone",
    currency: "SLL",
  },
  {
    name: "Singapore",
    dial_code: "+65",
    code: "SG",
    continent: "Asia",
    native: "Singapore",
    currency: "SGD",
  },
  {
    name: "Slovakia",
    dial_code: "+421",
    code: "SK",
    continent: "Europe",
    native: "Slovensko",
    currency: "EUR",
  },
  {
    name: "Slovenia",
    dial_code: "+386",
    code: "SI",
    continent: "Europe",
    native: "Slovenija",
    currency: "EUR",
  },
  {
    name: "Solomon Islands",
    dial_code: "+677",
    code: "SB",
    continent: "Oceania",
    native: "Solomon Islands",
    currency: "SBD",
  },
  {
    name: "Somalia",
    dial_code: "+252",
    code: "SO",
    continent: "Africa",
    native: "Soomaaliya",
    currency: "SOS",
  },
  {
    name: "South Africa",
    dial_code: "+27",
    code: "ZA",
    continent: "Africa",
    native: "South Africa",
    currency: "ZAR",
  },
  {
    name: "South Sudan",
    dial_code: "+211",
    code: "SS",
    continent: "Africa",
    native: "South Sudan",
    currency: "SSP",
  },
  {
    name: "South Georgia and the South Sandwich Islands",
    dial_code: "+500",
    code: "GS",
    continent: "Antarctica",
    native: "South Georgia",
    currency: "GBP",
  },
  {
    name: "Spain",
    dial_code: "+34",
    code: "ES",
    continent: "Europe",
    native: "España",
    currency: "EUR",
  },
  {
    name: "Sri Lanka",
    dial_code: "+94",
    code: "LK",
    continent: "Asia",
    native: "ශ්‍රී ලංකා",
    currency: "LKR",
  },
  {
    name: "Sudan",
    dial_code: "+249",
    code: "SD",
    continent: "Africa",
    native: "السودان",
    currency: "SDG",
  },
  {
    name: "Suriname",
    dial_code: "+597",
    code: "SR",
    continent: "South America",
    native: "Suriname",
    currency: "SRD",
  },
  {
    name: "Svalbard and Jan Mayen",
    dial_code: "+47",
    code: "SJ",
    continent: "Europe",
    native: "Svalbard og Jan Mayen",
    currency: "NOK",
  },
  {
    name: "Swaziland",
    dial_code: "+268",
    code: "SZ",
    continent: "Africa",
    native: "Swaziland",
    currency: "SZL",
  },
  {
    name: "Sweden",
    dial_code: "+46",
    code: "SE",
    continent: "Europe",
    native: "Sverige",
    currency: "SEK",
  },
  {
    name: "Switzerland",
    dial_code: "+41",
    code: "CH",
    continent: "Europe",
    native: "Schweiz",
    currency: "CHF",
  },
  {
    name: "Syrian Arab Republic",
    dial_code: "+963",
    code: "SY",
    continent: "Asia",
    native: "سوريا",
    currency: "SYP",
  },
  {
    name: "Taiwan",
    dial_code: "+886",
    code: "TW",
    continent: "Asia",
    native: "台灣",
    currency: "TWD",
  },
  {
    name: "Tajikistan",
    dial_code: "+992",
    code: "TJ",
    continent: "Asia",
    native: "Тоҷикистон",
    currency: "TJS",
  },
  {
    name: "Tanzania, United Republic of Tanzania",
    dial_code: "+255",
    code: "TZ",
    continent: "Africa",
    native: "Tanzania",
    currency: "TZS",
  },
  {
    name: "Thailand",
    dial_code: "+66",
    code: "TH",
    continent: "Asia",
    native: "ประเทศไทย",
    currency: "THB",
  },
  {
    name: "Timor-Leste",
    dial_code: "+670",
    code: "TL",
    continent: "Asia",
    native: "Timor-Leste",
    currency: "USD",
  },
  {
    name: "Togo",
    dial_code: "+228",
    code: "TG",
    continent: "Africa",
    native: "Togo",
    currency: "XOF",
  },
  {
    name: "Tokelau",
    dial_code: "+690",
    code: "TK",
    continent: "Oceania",
    native: "Tokelau",
    currency: "NZD",
  },
  {
    name: "Tonga",
    dial_code: "+676",
    code: "TO",
    continent: "Oceania",
    native: "Tonga",
    currency: "TOP",
  },
  {
    name: "Trinidad and Tobago",
    dial_code: "+1868",
    code: "TT",
    continent: "North America",
    native: "Trinidad and Tobago",
    currency: "TTD",
  },
  {
    name: "Tunisia",
    dial_code: "+216",
    code: "TN",
    continent: "Africa",
    native: "تونس",
    currency: "TND",
  },
  {
    name: "Turkey",
    dial_code: "+90",
    code: "TR",
    continent: "Asia",
    native: "Türkiye",
    currency: "TRY",
  },
  {
    name: "Turkmenistan",
    dial_code: "+993",
    code: "TM",
    continent: "Asia",
    native: "Türkmenistan",
    currency: "TMT",
  },
  {
    name: "Turks and Caicos Islands",
    dial_code: "+1649",
    code: "TC",
    continent: "North America",
    native: "Turks and Caicos Islands",
    currency: "USD",
  },
  {
    name: "Tuvalu",
    dial_code: "+688",
    code: "TV",
    continent: "Oceania",
    native: "Tuvalu",
    currency: "AUD",
  },
  {
    name: "Uganda",
    dial_code: "+256",
    code: "UG",
    continent: "Africa",
    native: "Uganda",
    currency: "UGX",
  },
  {
    name: "Ukraine",
    dial_code: "+380",
    code: "UA",
    continent: "Europe",
    native: "Україна",
    currency: "UAH",
  },
  {
    name: "United Arab Emirates",
    dial_code: "+971",
    code: "AE",
    continent: "Asia",
    native: "دولة الإمارات العربية المتحدة",
    currency: "AED",
  },
  {
    name: "United Kingdom",
    dial_code: "+44",
    code: "GB",
    continent: "Europe",
    native: "United Kingdom",
    currency: "GBP",
  },
  {
    name: "United States",
    dial_code: "+1",
    code: "US",
    continent: "North America",
    native: "United States",
    currency: "USD",
  },
  {
    name: "Uruguay",
    dial_code: "+598",
    code: "UY",
    continent: "South America",
    native: "Uruguay",
    currency: "UYU",
  },
  {
    name: "Uzbekistan",
    dial_code: "+998",
    code: "UZ",
    continent: "Asia",
    native: "Oʻzbekiston",
    currency: "UZS",
  },
  {
    name: "Vanuatu",
    dial_code: "+678",
    code: "VU",
    continent: "Oceania",
    native: "Vanuatu",
    currency: "VUV",
  },
  {
    name: "Venezuela, Bolivarian Republic of Venezuela",
    dial_code: "+58",
    code: "VE",
    continent: "South America",
    native: "Venezuela",
    currency: "VES",
  },
  {
    name: "Vietnam",
    dial_code: "+84",
    code: "VN",
    continent: "Asia",
    native: "Việt Nam",
    currency: "VND",
  },
  {
    name: "Virgin Islands, British",
    dial_code: "+1284",
    code: "VG",
    continent: "North America",
    native: "British Virgin Islands",
    currency: "USD",
  },
  {
    name: "Virgin Islands, U.S.",
    dial_code: "+1340",
    code: "VI",
    continent: "North America",
    native: "United States Virgin Islands",
    currency: "USD",
  },
  {
    name: "Wallis and Futuna",
    dial_code: "+681",
    code: "WF",
    continent: "Oceania",
    native: "Wallis et Futuna",
    currency: "XPF",
  },
  {
    name: "Yemen",
    dial_code: "+967",
    code: "YE",
    continent: "Asia",
    native: "اليمن",
    currency: "YER",
  },
  {
    name: "Zambia",
    dial_code: "+260",
    code: "ZM",
    continent: "Africa",
    native: "Zambia",
    currency: "ZMW",
  },
  {
    name: "Zimbabwe",
    dial_code: "+263",
    code: "ZW",
    continent: "Africa",
    native: "Zimbabwe",
    currency: "ZWL",
  },
  {
    name: "Autres",
    code: "XX",
    continent: "Autres",
    dial_code: "+000",
    native: "Autres",
    currency: "USD",
  },
];

export const mobileBreakpoint = "768px";

export const paymentMethods: PaymentMethod[] = [
  //   {
  //     id: "paypal",
  //     name: "PayPal",
  //     image: "/images/paypal.png",
  //   },
  //   {
  //     id: "stripe",
  //     name: "Stripe",
  //     image: "/images/stripe.png",
  //   },
  //   {
  //     id: "mobile-money",
  //     name: "Mobile Money",
  //     image: "/images/mobile-money.png",
  //   },
  //   {
  //     id: "card",
  //     name: "Carte Bancaire",
  //     image: "/images/card.png",
  //   },
  {
    id: "crypto",
    name: "Crypto Monnaie",
    image: "/images/crypto.png",
  },
  {
    id: "atPickup",
    name: "A la reception",
    image: "/images/atPickup.png",
  },
  {
    id: "kkPay",
    name: "kkPay",
    image: "/images/kkPay.png",
  },
  // {
  //   id: "AfterShipping",
  //   name: "Apres expedition",
  //   image: "/images/afterShipping.png",
  // },
];

export const OrderStatusText = {
  pending: "En attente",
  processing: "En cours de traitement",
  completed: "Commande complétée",
  cancelled: "Commande annulée",
  failed: "Commande échouée",
  refunded: "Remboursée",
  shipped: "Expédiée",
  delivered: "Livré",
  returned: "Retourné",
  lost: "Perdu",
  stolen: "Volé",
  damaged: "Endommagé",
  shipping: "En cours d'expédition",
  awaitingPayment: "En attente de paiement",
  awaitingFulfillment: "En attente de traitement",
  awaitingShipment: "En attente d'expédition",
  awaitingPickup: "En attente de récupération",
  partiallyShipped: "Partiellement expédié",
  partiallyDelivered: "Partiellement livré",
  partiallyReturned: "Partiellement retourné",
  partiallyRefunded: "Partiellement remboursé",
  disputed: "Contesté",
  unknown: "Inconnu",
};

// supported currencies xof, usd,eur
export const SupportedCurrencies = ["xof", "usd", "eur"];

export const SupportedCurrenciesSymbol = {
  xof: "CFA",
  usd: "$",
  eur: "€",
};

// en, es, de, fr, ar, pt, ru;

export const NavTranslation = {
  en: {
    home: "Home",
    market: "Market",
    order: "Orders",
    login: "Login",
    signup: "Signup",
    profile: "Profile",
    logout: "Logout",
    verifyOrder: "Verify Order",
    search: "Search",
    cart: "Cart",
    myOrders: "Orders",
    maBoutique: "Shop",
    addProduct: "Publish",
    myProducts: "Products",
    dashboard: "Dashboard",
    account: "Account",
    delivery: "Delivery",
  },
  fr: {
    home: "Accueil",
    market: "Marché",
    order: "Commandes",
    login: "Connecter",
    signup: "S'inscrire",
    profile: "Mon compte",
    logout: "Déconnexion",
    verifyOrder: "Vérifier une commande",
    search: "Rechercher",
    cart: "Panier",
    myOrders: "Commandes",
    maBoutique: "Boutique",
    addProduct: "Ajout",
    myProducts: "Produits",
    dashboard: "Statistiques",
    account: "Compte",
    delivery: "Livraison",
  },
  es: {
    home: "Inicio",
    market: "Mercado",
    order: "Pedidos",
    login: "Iniciar sesión",
    signup: "Regístrate",
    profile: "Perfil",
    logout: "Cerrar sesión",
    verifyOrder: "Verificar pedido",
    search: "Buscar",
    cart: "Carrito",
    myOrders: "Mis pedidos",
    maBoutique: "Mi tienda",
    addProduct: "Añadir producto",
    myProducts: "Mis productos",
    dashboard: "Tablero",
    account: "Cuenta",
    delivery: "Entrega",
  },
  de: {
    home: "Zuhause",
    market: "Markt",
    order: "Bestellungen",
    login: "Anmeldung",
    signup: "Anmelden",
    profile: "Profil",
    logout: "Ausloggen",
    verifyOrder: "Bestellung überprüfen",
    search: "Suche",
    cart: "Warenkorb",
    myOrders: "Meine Bestellungen",
    maBoutique: "Mein Geschäft",
    addProduct: "Produkt hinzufügen",
    myProducts: "Meine Produkte",
    dashboard: "Instrumententafel",
    account: "Konto",
    delivery: "Lieferung",
  },
  ar: {
    home: "الصفحة الرئيسية",
    market: "السوق",
    order: "طلب",
    login: "تسجيل الدخول",
    signup: "سجل",
    profile: "الملف الشخصي",
    logout: "تسجيل خروج",
    verifyOrder: "تحقق من الطلب",
    search: "بحث",
    cart: "عربة التسوق",
    myOrders: "طلباتي",
    maBoutique: "متجري",
    addProduct: "إضافة منتج",
    myProducts: "منتجاتي",
    dashboard: "لوحة القيادة",
    account: "الحساب",
    delivery: "توصيل",
  },
  pt: {
    home: "Casa",
    market: "Mercado",
    order: "Ordens",
    login: "Entrar",
    signup: "Inscrever-se",
    profile: "Perfil",
    logout: "Sair",
    verifyOrder: "Verificar pedido",
    search: "Procurar",
    cart: "Carrinho",
    myOrders: "Minhas ordens",
    maBoutique: "Minha loja",
    addProduct: "Adicionar produto",
    myProducts: "Meus produtos",
    dashboard: "Painel",
    account: "Conta",
    delivery: "Entrega",
  },
  ru: {
    home: "Главная",
    market: "Рынок",
    order: "Заказы",
    login: "Авторизоваться",
    signup: "Зарегистрироваться",
    profile: "Профиль",
    logout: "Выйти",
    verifyOrder: "Проверить заказ",
    search: "Поиск",
    cart: "Корзина",
    myOrders: "Мои заказы",
    maBoutique: "Мой магазин",
    addProduct: "Добавить продукт",
    myProducts: "Мои продукты",
    dashboard: "Приборная панель",
    account: "Счет",
    delivery: "Доставка",
  },
};

export const SupportedLanguages = ["en", "fr", "es", "de", "ar", "pt", "ru"];

export const SupportedCurrencyTranslation = {
  en: {
    xof: "West African CFA franc",
    usd: "United States Dollar",
    eur: "Euro",
  },
  fr: {
    xof: "Franc CFA",
    usd: "Dollar américain",
    eur: "Euro",
  },
  es: {
    xof: "Franco CFA",
    usd: "Dólar estadounidense",
    eur: "Euro",
  },
  de: {
    xof: "Westafrikanischer CFA-Franc",
    usd: "US-Dollar",
    eur: "Euro",
  },
  ar: {
    xof: "فرنك غرب أفريقي",
    usd: "الدولار الأمريكي",
    eur: "اليورو",
  },
  pt: {
    xof: "Franco CFA",
    usd: "Dólar dos Estados Unidos",
    eur: "Euro",
  },
  ru: {
    xof: "Франк КФА",
    usd: "Доллар США",
    eur: "Евро",
  },
};
// paymentMethods translation
export const PaymentMethodsTranslation = [
  {
    en: {
      id: "crypto",
      name: "Crypto Currency",
    },
    fr: {
      id: "crypto",
      name: "Crypto Monnaie",
    },
    es: {
      id: "crypto",
      name: "Criptomoneda",
    },
    de: {
      id: "crypto",
      name: "Kryptowährung",
    },
    ar: {
      id: "crypto",
      name: "عملة معماة",
    },
    pt: {
      id: "crypto",
      name: "Criptomoeda",
    },
    ru: {
      id: "crypto",
      name: "Криптовалюта",
    },
  },
  {
    en: {
      id: "kkPay",
      name: "KKPay (Mobile Money, Bank Card)",
    },
    fr: {
      id: "kkPay",
      name: "KKPay (Mobile Money, Carte Bancaire)",
    },
    es: {
      id: "kkPay",
      name: "KKPay (Dinero móvil, tarjeta bancaria)",
    },
    de: {
      id: "kkPay",
      name: "KKPay (Mobile Money, Bankkarte)",
    },
    ar: {
      id: "kkPay",
      name: "KKPay (المال المحمول ، بطاقة بنكية)",
    },
    pt: {
      id: "kkPay",
      name: "KKPay (Dinheiro móvel, Cartão bancário)",
    },
    ru: {
      id: "kkPay",
      name: "KKPay (Мобильные деньги, банковская карта)",
    },
  },
];

// OrderStatusText translation
export const OrderStatusTextTranslation = {
  en: {
    pending: "Pending",
    processing: "Processing",
    completed: "Completed",
    cancelled: "Cancelled",
    failed: "Failed",
    refunded: "Refunded",
    shipped: "Shipped",
    delivered: "Delivered",
    returned: "Returned",
    lost: "Lost",
    stolen: "Stolen",
    damaged: "Damaged",
    shipping: "Shipping",
    awaitingPayment: "Awaiting Payment",
    awaitingFulfillment: "Awaiting Fulfillment",
    awaitingShipment: "Awaiting Shipment",
    awaitingPickup: "Awaiting Pickup",
    partiallyShipped: "Partially Shipped",
    partiallyDelivered: "Partially Delivered",
    partiallyReturned: "Partially Returned",
    partiallyRefunded: "Partially Refunded",
    disputed: "Disputed",
    unknown: "Unknown",
  },
  fr: {
    pending: "En attente",
    processing: "En cours de traitement",
    completed: "Commande complétée",
    cancelled: "Commande annulée",
    failed: "Commande échouée",
    refunded: "Remboursée",
    shipped: "Expédiée",
    delivered: "Livré",
    returned: "Retourné",
    lost: "Perdu",
    stolen: "Volé",
    damaged: "Endommagé",
    shipping: "En cours d'expédition",
    awaitingPayment: "En attente de paiement",
    awaitingFulfillment: "En attente de traitement",
    awaitingShipment: "En attente d'expédition",
    awaitingPickup: "En attente de récupération",
    partiallyShipped: "Partiellement expédié",
    partiallyDelivered: "Partiellement livré",
    partiallyReturned: "Partiellement retourné",
    partiallyRefunded: "Partiellement remboursé",
    disputed: "Contesté",
    unknown: "Inconnu",
  },
  es: {
    pending: "Pendiente",
    processing: "Procesando",
    completed: "Completado",
    cancelled: "Cancelado",
    failed: "Fallido",
    refunded: "Reembolsado",
    shipped: "Enviado",
    delivered: "Entregado",
    returned: "Devuelto",
    lost: "Perdido",
    stolen: "Robado",
    damaged: "Dañado",
    shipping: "Envío",
    awaitingPayment: "Esperando pago",
    awaitingFulfillment: "Esperando cumplimiento",
    awaitingShipment: "Esperando envío",
    awaitingPickup: "Esperando recogida",
    partiallyShipped: "Parcialmente enviado",
    partiallyDelivered: "Parcialmente entregado",
    partiallyReturned: "Parcialmente devuelto",
    partiallyRefunded: "Parcialmente reembolsado",
    disputed: "Disputado",
    unknown: "Desconocido",
  },
  de: {
    pending: "Ausstehend",
    processing: "In Bearbeitung",
    completed: "Abgeschlossen",
    cancelled: "Abgebrochen",
    failed: "Gescheitert",
    refunded: "Erstattet",
    shipped: "Versendet",
    delivered: "Geliefert",
    returned: "Zurückgegeben",
    lost: "Verloren",
    stolen: "Gestohlen",
    damaged: "Beschädigt",
    shipping: "Versand",
    awaitingPayment: "Zahlung ausstehend",
    awaitingFulfillment: "Ausstehende Erfüllung",
    awaitingShipment: "Ausstehender Versand",
    awaitingPickup: "Abholung ausstehend",
    partiallyShipped: "Teilweise versendet",
    partiallyDelivered: "Teilweise geliefert",
    partiallyReturned: "Teilweise zurückgegeben",
    partiallyRefunded: "Teilweise erstattet",
    disputed: "Umgstritten",
    unknown: "Unbekannt",
  },
  ar: {
    pending: "قيد الانتظار",
    processing: "معالجة",
    completed: "مكتمل",
    cancelled: "ألغيت",
    failed: "فشل",
    refunded: "مسترد",
    shipped: "تم الشحن",
    delivered: "تم التوصيل",
    returned: "تم الإرجاع",
    lost: "ضائع",
    stolen: "مسروق",
    damaged: "تالف",
    shipping: "شحن",
    awaitingPayment: "في انتظار الدفع",
    awaitingFulfillment: "في انتظار الوفاء",
    awaitingShipment: "في انتظار الشحن",
    awaitingPickup: "في انتظار الاستلام",
    partiallyShipped: "تم الشحن جزئيا",
    partiallyDelivered: "تم التوصيل جزئيا",
    partiallyReturned: "تم الإرجاع جزئيا",
    partiallyRefunded: "تم الاسترداد جزئيا",
    disputed: "متنازع عليه",
    unknown: "غير معروف",
  },
  pt: {
    pending: "Pendente",
    processing: "Processando",
    completed: "Concluído",
    cancelled: "Cancelado",
    failed: "Falhou",
    refunded: "Reembolsado",
    shipped: "Enviado",
    delivered: "Entregue",
    returned: "Devolvido",
    lost: "Perdido",
    stolen: "Roubado",
    damaged: "Danificado",
    shipping: "Envio",
    awaitingPayment: "Aguardando pagamento",
    awaitingFulfillment: "Aguardando cumprimento",
    awaitingShipment: "Aguardando envio",
    awaitingPickup: "Aguardando retirada",
    partiallyShipped: "Parcialmente enviado",
    partiallyDelivered: "Parcialmente entregue",
    partiallyReturned: "Parcialmente devolvido",
    partiallyRefunded: "Parcialmente reembolsado",
    disputed: "Contestado",
    unknown: "Desconhecido",
  },
  ru: {
    pending: "В ожидании",
    processing: "Обработка",
    completed: "Завершено",
    cancelled: "Отменено",
    failed: "Не удалось",
    refunded: "Возвращено",
    shipped: "Отправлено",
    delivered: "Доставлено",
    returned: "Возвращено",
    lost: "Потеряно",
    stolen: "Украдено",
    damaged: "Повреждено",
    shipping: "Доставка",
    awaitingPayment: "Ожидание оплаты",
    awaitingFulfillment: "Ожидание выполнения",
    awaitingShipment: "Ожидание отправки",
    awaitingPickup: "Ожидание забора",
    partiallyShipped: "Частично отправлено",
    partiallyDelivered: "Частично доставлено",
    partiallyReturned: "Частично возвращено",
    partiallyRefunded: "Частично возвращено",
    disputed: "Оспаривается",
    unknown: "Неизвестно",
  },
};

export const OrderStatusColor = {
  pending: "orange",
  processing: "blue",
  completed: "green",
  cancelled: "red",
  failed: "red",
  refunded: "green",
  shipped: "blue",
  delivered: "green",
  returned: "red",
  lost: "red",
  stolen: "red",
  damaged: "red",
  shipping: "blue",
  awaitingPayment: "orange",
  awaitingFulfillment: "orange",
  awaitingShipment: "orange",
  awaitingPickup: "orange",
  partiallyShipped: "orange",
  partiallyDelivered: "orange",
  partiallyReturned: "orange",
  partiallyRefunded: "orange",
  disputed: "red",
  unknown: "orange",
};

export const NavShopElements = [
  {
    title: {
      fr: "Boutique",
      en: "My Shop",
      es: "Mi Tienda",
      de: "Mein Geschäft",
      ar: "متجري",
      pt: "Minha Loja",
      ru: "Мой магазин",
    },
    items: [
      {
        fr: "Tableau de bord",
        en: "Dashboard",
        es: "Tablero",
        de: "Instrumententafel",
        ar: "لوحة القيادة",
        pt: "Painel",
        ru: "Приборная панель",
      },
      {
        fr: "Ajouter un produit",
        en: "Add Product",
        es: "Añadir producto",
        de: "Produkt hinzufügen",
        ar: "إضافة منتج",
        pt: "Adicionar produto",
        ru: "Добавить продукт",
      },
      {
        fr: "Mes produits",
        en: "My Products",
        es: "Mis productos",
        de: "Meine Produkte",
        ar: "منتجاتي",
        pt: "Meus produtos",
        ru: "Мои продукты",
      },
      {
        fr: "Mes commandes",
        en: "My Orders",
        es: "Mis pedidos",
        de: "Meine Bestellungen",
        ar: "طلباتي",
        pt: "Minhas ordens",
        ru: "Мои заказы",
      },
    ],
  },
];

export const NavElements = [
  {
    title: {
      fr: "Pagnes",
      en: "Loincloths",
      es: "Pañuelos",
      de: "Lendenschurze",
      ar: "لفائف",
      pt: "Panos",
      ru: "Парчи",
    },
    // items: ["Uniwax", "Chiganvy", "Ankara Wax", "Autres"],
    items: [
      {
        fr: "Uniwax",
        en: "Uniwax",
        es: "Uniwax",
        de: "Uniwax",
        ar: "Uniwax",
        pt: "Uniwax",
        ru: "Uniwax",
      },
      {
        fr: "Chiganvy",
        en: "Chiganvy",
        es: "Chiganvy",
        de: "Chiganvy",
        ar: "Chiganvy",
        pt: "Chiganvy",
        ru: "Chiganvy",
      },
      {
        fr: "Ankara Wax",
        en: "Ankara Wax",
        es: "Ankara Wax",
        de: "Ankara Wax",
        ar: "Ankara Wax",
        pt: "Ankara Wax",
        ru: "Ankara Wax",
      },
      {
        fr: "Autres",
        en: "Others",
        es: "Otros",
        de: "Andere",
        ar: "آخرين",
        pt: "Outros",
        ru: "Другие",
      },
    ],
  },
  {
    title: {
      fr: "Ustensiles",
      en: "Utensils",
      es: "Utensilios",
      de: "Utensilien",
      ar: "أواني",
      pt: "Utensílios",
      ru: "Посуда",
    },
    items: [
      {
        fr: "Glacières",
        en: "Coolers",
        es: "Enfriadores",
        de: "Kühler",
        ar: "مبردات",
        pt: "Refrigeradores",
        ru: "Охладители",
      },
      {
        fr: "Casseroles",
        en: "Pots",
        es: "Ollas",
        de: "Töpfe",
        ar: "أواني",
        pt: "Panelas",
        ru: "Кастрюли",
      },
      {
        fr: "Marmittes",
        en: "Pans",
        es: "Sartenes",
        de: "Pfannen",
        ar: "مقالي",
        pt: "Panelas",
        ru: "Сковороды",
      },
      {
        fr: "Assiettes",
        en: "Plates",
        es: "Platos",
        de: "Teller",
        ar: "صحون",
        pt: "Pratos",
        ru: "Тарелки",
      },
      {
        fr: "Verres",
        en: "Glasses",
        es: "Vasos",
        de: "Gläser",
        ar: "أكواب",
        pt: "Copos",
        ru: "Стаканы",
      },
      {
        fr: "Autres",
        en: "Others",
        es: "Otros",
        de: "Andere",
        ar: "آخرين",
        pt: "Outros",
        ru: "Другие",
      },
    ],
  },
  {
    title: {
      fr: "Vêtements",
      en: "Clothing",
      es: "Ropa",
      de: "Kleidung",
      ar: "ملابس",
      pt: "Roupas",
      ru: "Одежда",
    },
    // items: ["Fillette", "Garçon", "Autres"],
    items: [
      {
        fr: "Fillette",
        en: "Girl",
        es: "Niña",
        de: "Mädchen",
        ar: "فتاة",
        pt: "Menina",
        ru: "Девочка",
      },
      {
        fr: "Garçon",
        en: "Boy",
        es: "Niño",
        de: "Junge",
        ar: "ولد",
        pt: "Menino",
        ru: "Мальчик",
      },
      {
        fr: "Autres",
        en: "Others",
        es: "Otros",
        de: "Andere",
        ar: "آخرين",
        pt: "Outros",
        ru: "Другие",
      },
    ],
  },
  {
    // title: "Accessoires",
    title: {
      fr: "Accessoires",
      en: "Accessories",
      es: "Accesorios",
      de: "Zubehör",
      ar: "إكسسوارات",
      pt: "Acessórios",
      ru: "Аксессуары",
    },
    // items: ["Bijoux", "Sacs", "Perruques", "Autres"],
    items: [
      {
        fr: "Bijoux",
        en: "Jewelry",
        es: "Joyas",
        de: "Schmuck",
        ar: "مجوهرات",
        pt: "Joias",
        ru: "Ювелирные изделия",
      },
      {
        fr: "Sacs",
        en: "Bags",
        es: "Bolsas",
        de: "Taschen",
        ar: "حقائب",
        pt: "Bolsas",
        ru: "Сумки",
      },
      {
        fr: "Perruques",
        en: "Wigs",
        es: "Pelucas",
        de: "Perücken",
        ar: "شعر مستعار",
        pt: "Perucas",
        ru: "Парики",
      },
      {
        fr: "Autres",
        en: "Others",
        es: "Otros",
        de: "Andere",
        ar: "آخرين",
        pt: "Outros",
        ru: "Другие",
      },
    ],
  },
];

export const NavElementsIcons = [
  <GiRolledCloth
    size={20}
    color={defaultColor}
    style={{
      marginRight: "10px",
    }}
  />,
  <FaKitchenSet
    size={20}
    color={defaultColor}
    style={{
      marginRight: "10px",
    }}
  />,
  <GiClothes
    size={20}
    color={defaultColor}
    style={{
      marginRight: "10px",
    }}
  />,
  <CgMoreO
    size={20}
    color={defaultColor}
    style={{
      marginRight: "10px",
    }}
  />,
];

//above currenncies name, symbol, chain, fullName
export const supportedCurrenciesExtended: Currency[] = [
  {
    name: "USD Coin",
    symbol: "usdcmatic",
    chain: "polygon",
    fullName: "USD Coin (Matic)",
    symbolUtf8: "usdcmatic",
    minAmount: 0,
  },
  {
    name: "Matic",
    symbol: "maticmainnet",
    chain: "polygon",
    fullName: "Matic",
    symbolUtf8: "maticmainnet",
    minAmount: 0,
  },
  {
    name: "Standard Tokenization Protocol",
    symbol: "stpt",
    chain: "ethereum",
    fullName: "Standard Tokenization Protocol",
    symbolUtf8: "stpt",
    minAmount: 0,
  },
  {
    name: "USD Tether",
    symbol: "usdterc20",
    chain: "ethereum",
    fullName: "USD Tether (ERC20)",
    symbolUtf8: "usdterc20",
    minAmount: 0,
  },
  {
    name: "USD Tether",
    symbol: "usdttrc20",
    chain: "tron",
    fullName: "USD Tether (TRC20)",
    symbolUtf8: "usdttrc20",
    minAmount: 0,
  },
  {
    name: "USD",
    symbol: "usd",
    chain: "Centralized",
    fullName: "USD",
    symbolUtf8: "$",
    minAmount: 0,
  },
  {
    name: "Euro",
    symbol: "eur",
    chain: "Centralized",
    fullName: "Euro",
    symbolUtf8: "€",
    minAmount: 0,
  },
  {
    name: "FCFA",
    symbol: "xof",
    chain: "Centralized",
    fullName: "West African CFA franc",
    symbolUtf8: "CFA",
    minAmount: 0,
  },
  {
    name: "USD Coin",
    symbol: "usdc",
    chain: "ethereum",
    fullName: "USD Coin",
    symbolUtf8: "usdc",
    minAmount: 0,
  },
  {
    name: "USD Tether",
    symbol: "usdtbsc",
    chain: "binance-smart-chain",
    fullName: "USD Tether (BSC)",
    symbolUtf8: "usdtbsc",
    minAmount: 0,
  },
  {
    name: "USD Tether",
    symbol: "usddtrc20",
    chain: "tron",
    fullName: "USD Tether (TRC20)",
    symbolUtf8: "usddtrc20",
    minAmount: 0,
  },
  {
    name: "USD Tether",
    symbol: "usdtsol",
    chain: "solana",
    fullName: "USD Tether (SOL)",
    symbolUtf8: "usdtsol",
    minAmount: 0,
  },
  {
    name: "USD Protocol",
    symbol: "usdp",
    chain: "ethereum",
    fullName: "USD Protocol",
    symbolUtf8: "usdp",
    minAmount: 0,
  },
  {
    name: "TrueUSD",
    symbol: "tusd",
    chain: "ethereum",
    fullName: "TrueUSD",
    symbolUtf8: "tusd",
    minAmount: 0,
  },
  {
    name: "Gemini Dollar",
    symbol: "gusd",
    chain: "ethereum",
    fullName: "Gemini Dollar",
    symbolUtf8: "gusd",
    minAmount: 0,
  },
  {
    name: "Aave",
    symbol: "aave",
    chain: "ethereum",
    fullName: "Aave",
    symbolUtf8: "aave",
    minAmount: 0,
  },
  {
    name: "Cosmos",
    symbol: "atom",
    chain: "cosmos",
    fullName: "Cosmos (ATOM)",
    symbolUtf8: "atom",
    minAmount: 0,
  },
  {
    name: "Shiba Inu",
    symbol: "shib",
    chain: "ethereum",
    fullName: "Shiba Inu",
    symbolUtf8: "shib",
    minAmount: 0,
  },
  {
    name: "Bitcoin",
    symbol: "btc",
    chain: "bitcoin",
    fullName: "Bitcoin",
    symbolUtf8: "btc",
    minAmount: 0,
  },
  {
    name: "Monero",
    symbol: "xmr",
    chain: "monero",
    fullName: "Monero",
    symbolUtf8: "xmr",
    minAmount: 0,
  },
  {
    name: "Ripple",
    symbol: "xrp",
    chain: "ripple",
    fullName: "Ripple",
    symbolUtf8: "xrp",
    minAmount: 0,
  },
  {
    name: "Uniswap",
    symbol: "uni",
    chain: "ethereum",
    fullName: "Uniswap",
    symbolUtf8: "uni",
    minAmount: 0,
  },
  {
    name: "Ethereum",
    symbol: "eth",
    chain: "ethereum",
    fullName: "Ethereum",
    symbolUtf8: "eth",
    minAmount: 0,
  },
  {
    name: "Ethereum",
    symbol: "ethbsc",
    chain: "binance-smart-chain",
    fullName: "Ethereum (BSC)",
    symbolUtf8: "ethbsc",
    minAmount: 0,
  },
  {
    name: "Ethereum",
    symbol: "ethw",
    chain: "ethereum",
    fullName: "wrapped Ethereum",
    symbolUtf8: "ethw",
    minAmount: 0,
  },
  {
    name: "Binance Coin",
    symbol: "bnbmainnet",
    chain: "binance-smart-chain",
    fullName: "Binance Coin",
    symbolUtf8: "bnbmainnet",
    minAmount: 0,
  },
  {
    name: "Binance Coin",
    symbol: "bnbbsc",
    chain: "binance-smart-chain",
    fullName: "Binance Coin (BSC)",
    symbolUtf8: "bnbbsc",
    minAmount: 0,
  },
  {
    name: "Dogecoin",
    symbol: "dogecoin",
    chain: "dogecoin",
    fullName: "Dogecoin",
    symbolUtf8: "dogecoin",
    minAmount: 0,
  },
];
