import Head from "next/head";
import { useState } from "react";
import { Burger } from "@mantine/core";
import { useMediaQuery } from "@mantine/hooks";
import NavDrawer from "./components/Navs/drawer/_drawer";
import Side from "./components/Navs/side/_side";
import {
  StyledHeader,
  StyledMain,
  StyledContent,
  StyledNav,
} from "../styled/general";
export default function Dashboard() {
  const [opened, setOpened] = useState<boolean>(false);
  const matches = useMediaQuery("(max-width: 900px)");

  return (
    <>
      <Head>
        <title>Nextjs: Appshell</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <StyledHeader height={60} p="lg" style={{}}>
        <div></div>
        <Burger
          opened={opened}
          onClick={() => setOpened((o) => !o)}
          title={""}
          style={{
            display: matches ? "block" : "none",
          }}
        />
      </StyledHeader>
      <StyledMain>
        <StyledNav>
          <NavDrawer opened={opened} setOpened={setOpened} />
          <Side />
        </StyledNav>
        <StyledContent>
          <h1>Dashboard</h1>
        </StyledContent>
      </StyledMain>
    </>
  );
}
